// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqQ_G_Wjw3zyJR7nulKx8Pbh2OGrV62w',
    appId: '1:1021719709382:web:58d80ac819c4202833b9c7',
    messagingSenderId: '1021719709382',
    projectId: 'globalee-36b7d',
    authDomain: 'globalee-36b7d.firebaseapp.com',
    storageBucket: 'globalee-36b7d.appspot.com',
    measurementId: 'G-TW3E0L3JXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCY9I2kwNgx7VHFx-x-30cxBW_IIQekpI',
    appId: '1:1021719709382:android:6cd09fa72bce9b9433b9c7',
    messagingSenderId: '1021719709382',
    projectId: 'globalee-36b7d',
    storageBucket: 'globalee-36b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuqDbzee2AKmJUwtofzWoy2D0SgBrq5rg',
    appId: '1:1021719709382:ios:a4de78659d52be2033b9c7',
    messagingSenderId: '1021719709382',
    projectId: 'globalee-36b7d',
    storageBucket: 'globalee-36b7d.appspot.com',
    iosClientId: '1021719709382-27ttj3nhhrm6cuibik83ml8k3e701avq.apps.googleusercontent.com',
    iosBundleId: 'com.example.globaleeAppDevelopment',
  );
}
